name: GitHub Org Repo Scanner

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests pandas openpyxl

    - name: Run the scan script
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        MY_GITHUB_ORG: ${{ secrets.MY_GITHUB_ORG }}
      run: python scan_org_repos.py

    - name: Commit and push Excel report
      env:
        MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add repos_report.xlsx
        git commit -m "Auto-uploaded repo report" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${MY_GITHUB_PAT}@github.com/${{ github.repository }}
        git push origin HEAD:main
